#!/usr/bin/env bash
# GitNexus re-index wrapper for Huxley
# Usage: tools/gitnexus-reindex.sh [--force]
#
# Why this wrapper exists:
# `gitnexus analyze` always regenerates AGENTS.md and expands the
# <!-- gitnexus:start/end --> block in CLAUDE.md to ~60 lines.
# Huxley keeps a compact CLAUDE.md block instead, and the repo-root
# AGENTS.md is Huxley's own personalized portable-identity file (see
# SOUL.md) — NOT a GitNexus artifact. This wrapper runs the index, then
# restores the compact CLAUDE.md block and the pre-index AGENTS.md.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# Verify gitnexus markers exist before proceeding
if ! grep -q '<!-- gitnexus:start -->' CLAUDE.md || ! grep -q '<!-- gitnexus:end -->' CLAUDE.md; then
    echo "ERROR: gitnexus start/end markers not found in CLAUDE.md — aborting to prevent bloat" >&2
    exit 1
fi

# Save compact CLAUDE.md gitnexus block
COMPACT_BLOCK=$(sed -n '/<!-- gitnexus:start -->/,/<!-- gitnexus:end -->/p' CLAUDE.md)

# Save AGENTS.md: `gitnexus analyze` overwrites it with a generated file,
# but this repo's AGENTS.md is a first-class identity file the user
# personalizes ("Personalize Me" section). The trap restores it even if the
# index run aborts midway (set -e).
AGENTS_BACKUP=""
if [ -f AGENTS.md ]; then
    AGENTS_BACKUP="$(mktemp "${TMPDIR:-/tmp}/agents-md-backup.XXXXXX")"
    cp AGENTS.md "$AGENTS_BACKUP"
    trap '[ -n "$AGENTS_BACKUP" ] && [ -f "$AGENTS_BACKUP" ] && cp "$AGENTS_BACKUP" AGENTS.md && rm -f "$AGENTS_BACKUP"' EXIT
fi

# Run gitnexus analyze (pass through any flags like --force)
gitnexus analyze . "$@"

# Restore compact CLAUDE.md block (gitnexus re-expands it)
# Pass via env var to avoid shell injection in python -c string
if [ -n "$COMPACT_BLOCK" ]; then
    COMPACT_BLOCK="$COMPACT_BLOCK" python3 -c "
import re, os
with open('CLAUDE.md', 'r') as f:
    content = f.read()
compact = os.environ['COMPACT_BLOCK']
content = re.sub(
    r'<!-- gitnexus:start -->.*?<!-- gitnexus:end -->',
    lambda m: compact,
    content,
    flags=re.DOTALL
)
with open('CLAUDE.md', 'w') as f:
    f.write(content)
"
    echo "CLAUDE.md: compact GitNexus block restored"
fi

# Restore the pre-index AGENTS.md (or drop the generated one if this repo
# never had an AGENTS.md — nothing here uses a generated one).
if [ -n "$AGENTS_BACKUP" ]; then
    cp "$AGENTS_BACKUP" AGENTS.md
    rm -f "$AGENTS_BACKUP"
    trap - EXIT
    AGENTS_BACKUP=""
    echo "AGENTS.md: restored (repo identity file preserved)"
elif [ -f AGENTS.md ]; then
    rm AGENTS.md
    echo "AGENTS.md: removed (generated by GitNexus; this repo does not keep one)"
fi

echo "GitNexus re-index complete"
